export default function PrivacyPage() {
    return (
        <main className="mx-auto max-w-3xl px-4 py-24 sm:px-6 lg:px-8">
            <div className="prose prose-slate prose-indigo max-w-none">
                Terms of Service
                Effective Date: July 2026

                1. Acceptance of Terms
                By accessing or using SuperResAI, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.

                2. Description of Service
                SuperResAI provides AI-powered image upscaling and enhancement. The service is provided "as is," and we reserve the right to modify, suspend, or discontinue any part of the service at any time without notice.

                3. Acceptable Use
                You agree not to use SuperResAI to:

                Upload, process, or distribute illegal, non-consensual, or highly inappropriate material.

                Violate any applicable local, national, or international laws.

                Attempt to reverse-engineer our backend systems or overload our servers (e.g., via automated scraping or botting).

                4. Intellectual Property Rights

                Your Content: You retain all ownership rights to the original images you upload and the upscaled images generated by our service. We claim no ownership over your content.

                Our Service: The SuperResAI website, code, design, and branding are our intellectual property.

                5. Limitation of Liability
                Generative AI is unpredictable. We do not guarantee that the upscaled images will be perfectly accurate or free of visual artifacts. To the maximum extent permitted by law, SuperResAI and its creator shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.

                6. Fair Use and Abuse
                While the service is currently free, we monitor usage to prevent abuse that spikes our GPU costs. We reserve the right to rate-limit, suspend, or terminate accounts that exhibit unusually high traffic or abuse the platform.

                7. Governing Law
                These terms shall be governed and construed in accordance with the laws of Malaysia, without regard to its conflict of law provisions.
            </div>
        </main>
    );
}